// Mocks generated by Mockito 5.4.6 from annotations
// in frontend/test/domain/usecases/reserva/crear_reserva_usecase_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:frontend/domain/entities/reserva.dart' as _i2;
import 'package:frontend/domain/repositories/reserva_repository.dart' as _i3;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeReserva_0 extends _i1.SmartFake implements _i2.Reserva {
  _FakeReserva_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [ReservaRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockReservaRepository extends _i1.Mock implements _i3.ReservaRepository {
  MockReservaRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i2.Reserva> crearReserva(_i2.Reserva? reserva) =>
      (super.noSuchMethod(
            Invocation.method(#crearReserva, [reserva]),
            returnValue: _i4.Future<_i2.Reserva>.value(
              _FakeReserva_0(this, Invocation.method(#crearReserva, [reserva])),
            ),
          )
          as _i4.Future<_i2.Reserva>);

  @override
  _i4.Future<List<_i2.Reserva>> getTodasLasReservas() =>
      (super.noSuchMethod(
            Invocation.method(#getTodasLasReservas, []),
            returnValue: _i4.Future<List<_i2.Reserva>>.value(<_i2.Reserva>[]),
          )
          as _i4.Future<List<_i2.Reserva>>);

  @override
  _i4.Future<List<_i2.Reserva>> getReservasPorUsuario(String? usuarioId) =>
      (super.noSuchMethod(
            Invocation.method(#getReservasPorUsuario, [usuarioId]),
            returnValue: _i4.Future<List<_i2.Reserva>>.value(<_i2.Reserva>[]),
          )
          as _i4.Future<List<_i2.Reserva>>);

  @override
  _i4.Future<List<_i2.Reserva>> getReservasPorHabitacion(
    String? habitacionId,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getReservasPorHabitacion, [habitacionId]),
            returnValue: _i4.Future<List<_i2.Reserva>>.value(<_i2.Reserva>[]),
          )
          as _i4.Future<List<_i2.Reserva>>);

  @override
  _i4.Future<_i2.Reserva> getReservaById(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#getReservaById, [id]),
            returnValue: _i4.Future<_i2.Reserva>.value(
              _FakeReserva_0(this, Invocation.method(#getReservaById, [id])),
            ),
          )
          as _i4.Future<_i2.Reserva>);

  @override
  _i4.Future<void> cancelarReserva(String? reservaId) =>
      (super.noSuchMethod(
            Invocation.method(#cancelarReserva, [reservaId]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> actualizarEstado(String? reservaId, String? nuevoEstado) =>
      (super.noSuchMethod(
            Invocation.method(#actualizarEstado, [reservaId, nuevoEstado]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);
}
