// Mocks generated by Mockito 5.4.6 from annotations
// in frontend/test/unit/services/auth_repository_impl_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;
import 'dart:typed_data' as _i5;

import 'package:frontend/data/datasources/firebase/auth_datasource.dart' as _i3;
import 'package:frontend/data/models/usuario_model.dart' as _i2;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeUsuarioModel_0 extends _i1.SmartFake implements _i2.UsuarioModel {
  _FakeUsuarioModel_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [AuthDataSource].
///
/// See the documentation for Mockito's code generation for more information.
class MockAuthDataSource extends _i1.Mock implements _i3.AuthDataSource {
  MockAuthDataSource() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Stream<_i2.UsuarioModel?> get authStateChanges =>
      (super.noSuchMethod(
            Invocation.getter(#authStateChanges),
            returnValue: _i4.Stream<_i2.UsuarioModel?>.empty(),
          )
          as _i4.Stream<_i2.UsuarioModel?>);

  @override
  _i4.Future<_i2.UsuarioModel> loginConEmail(String? email, String? password) =>
      (super.noSuchMethod(
            Invocation.method(#loginConEmail, [email, password]),
            returnValue: _i4.Future<_i2.UsuarioModel>.value(
              _FakeUsuarioModel_0(
                this,
                Invocation.method(#loginConEmail, [email, password]),
              ),
            ),
          )
          as _i4.Future<_i2.UsuarioModel>);

  @override
  _i4.Future<_i2.UsuarioModel> registrarse({
    required String? nombre,
    required String? email,
    required String? password,
    required String? cedula,
    DateTime? fechaNacimiento,
    String? telefono,
    String? ubicacion,
    _i5.Uint8List? fotoBytes,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#registrarse, [], {
              #nombre: nombre,
              #email: email,
              #password: password,
              #cedula: cedula,
              #fechaNacimiento: fechaNacimiento,
              #telefono: telefono,
              #ubicacion: ubicacion,
              #fotoBytes: fotoBytes,
            }),
            returnValue: _i4.Future<_i2.UsuarioModel>.value(
              _FakeUsuarioModel_0(
                this,
                Invocation.method(#registrarse, [], {
                  #nombre: nombre,
                  #email: email,
                  #password: password,
                  #cedula: cedula,
                  #fechaNacimiento: fechaNacimiento,
                  #telefono: telefono,
                  #ubicacion: ubicacion,
                  #fotoBytes: fotoBytes,
                }),
              ),
            ),
          )
          as _i4.Future<_i2.UsuarioModel>);

  @override
  _i4.Future<_i2.UsuarioModel> loginConGoogle() =>
      (super.noSuchMethod(
            Invocation.method(#loginConGoogle, []),
            returnValue: _i4.Future<_i2.UsuarioModel>.value(
              _FakeUsuarioModel_0(this, Invocation.method(#loginConGoogle, [])),
            ),
          )
          as _i4.Future<_i2.UsuarioModel>);

  @override
  _i4.Future<void> cerrarSesion() =>
      (super.noSuchMethod(
            Invocation.method(#cerrarSesion, []),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<_i2.UsuarioModel?> getUsuarioActual() =>
      (super.noSuchMethod(
            Invocation.method(#getUsuarioActual, []),
            returnValue: _i4.Future<_i2.UsuarioModel?>.value(),
          )
          as _i4.Future<_i2.UsuarioModel?>);

  @override
  _i4.Future<_i2.UsuarioModel> actualizarPerfil({
    required String? uid,
    String? nombre,
    String? cedula,
    DateTime? fechaNacimiento,
    String? telefono,
    String? ubicacion,
    _i5.Uint8List? fotoBytes,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#actualizarPerfil, [], {
              #uid: uid,
              #nombre: nombre,
              #cedula: cedula,
              #fechaNacimiento: fechaNacimiento,
              #telefono: telefono,
              #ubicacion: ubicacion,
              #fotoBytes: fotoBytes,
            }),
            returnValue: _i4.Future<_i2.UsuarioModel>.value(
              _FakeUsuarioModel_0(
                this,
                Invocation.method(#actualizarPerfil, [], {
                  #uid: uid,
                  #nombre: nombre,
                  #cedula: cedula,
                  #fechaNacimiento: fechaNacimiento,
                  #telefono: telefono,
                  #ubicacion: ubicacion,
                  #fotoBytes: fotoBytes,
                }),
              ),
            ),
          )
          as _i4.Future<_i2.UsuarioModel>);

  @override
  _i4.Future<void> vincularPasswordAGoogle({required String? password}) =>
      (super.noSuchMethod(
            Invocation.method(#vincularPasswordAGoogle, [], {
              #password: password,
            }),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> enviarVerificacionEmail() =>
      (super.noSuchMethod(
            Invocation.method(#enviarVerificacionEmail, []),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> enviarCorreoRecuperacionPassword(String? email) =>
      (super.noSuchMethod(
            Invocation.method(#enviarCorreoRecuperacionPassword, [email]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<bool> verificarEmailConfirmado() =>
      (super.noSuchMethod(
            Invocation.method(#verificarEmailConfirmado, []),
            returnValue: _i4.Future<bool>.value(false),
          )
          as _i4.Future<bool>);

  @override
  _i4.Future<bool> esUsuarioSoloGoogle() =>
      (super.noSuchMethod(
            Invocation.method(#esUsuarioSoloGoogle, []),
            returnValue: _i4.Future<bool>.value(false),
          )
          as _i4.Future<bool>);

  @override
  _i4.Future<void> eliminarCuenta() =>
      (super.noSuchMethod(
            Invocation.method(#eliminarCuenta, []),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);
}
