// Mocks generated by Mockito 5.4.6 from annotations
// in frontend/test/unit/services/reserva_viewmodel_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:frontend/domain/entities/reserva.dart' as _i2;
import 'package:frontend/domain/usecases/habitacion/check_disponibilidad_usecase.dart'
    as _i9;
import 'package:frontend/domain/usecases/reserva/actualizar_estado_reserva_usecase.dart'
    as _i7;
import 'package:frontend/domain/usecases/reserva/cancelar_reserva_usecase.dart'
    as _i8;
import 'package:frontend/domain/usecases/reserva/crear_reserva_usecase.dart'
    as _i3;
import 'package:frontend/domain/usecases/reserva/get_historial_reservas_usecase.dart'
    as _i5;
import 'package:frontend/domain/usecases/reserva/get_todas_las_reservas_usecase.dart'
    as _i6;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeReserva_0 extends _i1.SmartFake implements _i2.Reserva {
  _FakeReserva_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [CrearReservaUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockCrearReservaUseCase extends _i1.Mock
    implements _i3.CrearReservaUseCase {
  MockCrearReservaUseCase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i2.Reserva> call(_i2.Reserva? reserva) =>
      (super.noSuchMethod(
            Invocation.method(#call, [reserva]),
            returnValue: _i4.Future<_i2.Reserva>.value(
              _FakeReserva_0(this, Invocation.method(#call, [reserva])),
            ),
          )
          as _i4.Future<_i2.Reserva>);
}

/// A class which mocks [GetHistorialReservasUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockGetHistorialReservasUseCase extends _i1.Mock
    implements _i5.GetHistorialReservasUseCase {
  MockGetHistorialReservasUseCase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<List<_i2.Reserva>> call(String? usuarioId) =>
      (super.noSuchMethod(
            Invocation.method(#call, [usuarioId]),
            returnValue: _i4.Future<List<_i2.Reserva>>.value(<_i2.Reserva>[]),
          )
          as _i4.Future<List<_i2.Reserva>>);
}

/// A class which mocks [GetTodasLasReservasUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockGetTodasLasReservasUseCase extends _i1.Mock
    implements _i6.GetTodasLasReservasUseCase {
  MockGetTodasLasReservasUseCase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<List<_i2.Reserva>> call() =>
      (super.noSuchMethod(
            Invocation.method(#call, []),
            returnValue: _i4.Future<List<_i2.Reserva>>.value(<_i2.Reserva>[]),
          )
          as _i4.Future<List<_i2.Reserva>>);
}

/// A class which mocks [ActualizarEstadoReservaUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockActualizarEstadoReservaUseCase extends _i1.Mock
    implements _i7.ActualizarEstadoReservaUseCase {
  MockActualizarEstadoReservaUseCase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<void> call(String? reservaId, String? nuevoEstado) =>
      (super.noSuchMethod(
            Invocation.method(#call, [reservaId, nuevoEstado]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);
}

/// A class which mocks [CancelarReservaUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockCancelarReservaUseCase extends _i1.Mock
    implements _i8.CancelarReservaUseCase {
  MockCancelarReservaUseCase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<void> call(String? reservaId) =>
      (super.noSuchMethod(
            Invocation.method(#call, [reservaId]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);
}

/// A class which mocks [CheckDisponibilidadUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockCheckDisponibilidadUseCase extends _i1.Mock
    implements _i9.CheckDisponibilidadUseCase {
  MockCheckDisponibilidadUseCase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<bool> call(
    String? habitacionId,
    DateTime? checkIn,
    DateTime? checkOut,
    int? cantidadSolicitada,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#call, [
              habitacionId,
              checkIn,
              checkOut,
              cantidadSolicitada,
            ]),
            returnValue: _i4.Future<bool>.value(false),
          )
          as _i4.Future<bool>);
}
