// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAZPrOkT4I4oPXrwj0oEnP7Ub-11TQXyg8',
    appId: '1:344844210027:web:891214205c4a7d50b2c62e',
    messagingSenderId: '344844210027',
    projectId: 'hostsigchos',
    authDomain: 'hostsigchos.firebaseapp.com',
    storageBucket: 'hostsigchos.firebasestorage.app',
    measurementId: 'G-Z176ZY6R70',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAyGNq3gQlKbgVo_xayPNRG4AZHcRPn_fg',
    appId: '1:344844210027:android:f08802e0a185fd07b2c62e',
    messagingSenderId: '344844210027',
    projectId: 'hostsigchos',
    storageBucket: 'hostsigchos.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCVavKA27JzLLF8D3Y-pMhftIZLaqBJfJk',
    appId: '1:344844210027:ios:c797a49711a50881b2c62e',
    messagingSenderId: '344844210027',
    projectId: 'hostsigchos',
    storageBucket: 'hostsigchos.firebasestorage.app',
    iosClientId:
        '344844210027-s6ckho6clpvo1de40ku2qtp78s2aj16p.apps.googleusercontent.com',
    iosBundleId: 'com.example.frontend',
  );
  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCVavKA27JzLLF8D3Y-pMhftIZLaqBJfJk',
    appId: '1:344844210027:ios:c797a49711a50881b2c62e',
    messagingSenderId: '344844210027',
    projectId: 'hostsigchos',
    storageBucket: 'hostsigchos.firebasestorage.app',
    iosClientId:
        '344844210027-s6ckho6clpvo1de40ku2qtp78s2aj16p.apps.googleusercontent.com',
    iosBundleId: 'com.example.frontend',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAZPrOkT4I4oPXrwj0oEnP7Ub-11TQXyg8',
    appId: '1:344844210027:web:bbcf8ca3e19e2054b2c62e',
    messagingSenderId: '344844210027',
    projectId: 'hostsigchos',
    authDomain: 'hostsigchos.firebaseapp.com',
    storageBucket: 'hostsigchos.firebasestorage.app',
    measurementId: 'G-MDXDS9GFPX',
  );
}
