// Mocks generated by Mockito 5.4.6 from annotations
// in frontend/test/widget/screens/home_screen_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i17;
import 'dart:typed_data' as _i19;
import 'dart:ui' as _i15;

import 'package:flutter/material.dart' as _i22;
import 'package:frontend/domain/entities/habitacion.dart' as _i24;
import 'package:frontend/domain/entities/hosteria.dart' as _i21;
import 'package:frontend/domain/entities/notificacion.dart' as _i31;
import 'package:frontend/domain/entities/reserva.dart' as _i26;
import 'package:frontend/domain/entities/usuario.dart' as _i18;
import 'package:frontend/domain/repositories/auth_repository.dart' as _i11;
import 'package:frontend/domain/usecases/auth/actualizar_perfil_usecase.dart'
    as _i6;
import 'package:frontend/domain/usecases/auth/eliminar_cuenta_usecase.dart'
    as _i10;
import 'package:frontend/domain/usecases/auth/google_signin_usecase.dart'
    as _i4;
import 'package:frontend/domain/usecases/auth/login_usecase.dart' as _i2;
import 'package:frontend/domain/usecases/auth/logout_usecase.dart' as _i5;
import 'package:frontend/domain/usecases/auth/recuperar_password_usecase.dart'
    as _i9;
import 'package:frontend/domain/usecases/auth/register_usecase.dart' as _i3;
import 'package:frontend/domain/usecases/auth/verificar_email_usecase.dart'
    as _i8;
import 'package:frontend/domain/usecases/auth/vincular_password_usecase.dart'
    as _i7;
import 'package:frontend/domain/usecases/habitacion/check_disponibilidad_usecase.dart'
    as _i13;
import 'package:frontend/domain/usecases/habitacion/get_habitaciones_usecase.dart'
    as _i12;
import 'package:frontend/domain/usecases/habitacion/get_todas_las_habitaciones_usecase.dart'
    as _i14;
import 'package:frontend/presentation/viewmodels/auth_viewmodel.dart' as _i16;
import 'package:frontend/presentation/viewmodels/habitacion_viewmodel.dart'
    as _i23;
import 'package:frontend/presentation/viewmodels/hosteria_viewmodel.dart'
    as _i20;
import 'package:frontend/presentation/viewmodels/locale_viewmodel.dart' as _i27;
import 'package:frontend/presentation/viewmodels/notificacion_viewmodel.dart'
    as _i30;
import 'package:frontend/presentation/viewmodels/reserva_viewmodel.dart'
    as _i25;
import 'package:frontend/presentation/viewmodels/weather_viewmodel.dart'
    as _i28;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i29;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeLoginUseCase_0 extends _i1.SmartFake implements _i2.LoginUseCase {
  _FakeLoginUseCase_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeRegisterUseCase_1 extends _i1.SmartFake
    implements _i3.RegisterUseCase {
  _FakeRegisterUseCase_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeGoogleSignInUseCase_2 extends _i1.SmartFake
    implements _i4.GoogleSignInUseCase {
  _FakeGoogleSignInUseCase_2(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeLogoutUseCase_3 extends _i1.SmartFake implements _i5.LogoutUseCase {
  _FakeLogoutUseCase_3(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeActualizarPerfilUseCase_4 extends _i1.SmartFake
    implements _i6.ActualizarPerfilUseCase {
  _FakeActualizarPerfilUseCase_4(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeVincularPasswordUseCase_5 extends _i1.SmartFake
    implements _i7.VincularPasswordUseCase {
  _FakeVincularPasswordUseCase_5(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeVerificarEmailUseCase_6 extends _i1.SmartFake
    implements _i8.VerificarEmailUseCase {
  _FakeVerificarEmailUseCase_6(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeRecuperarPasswordUseCase_7 extends _i1.SmartFake
    implements _i9.RecuperarPasswordUseCase {
  _FakeRecuperarPasswordUseCase_7(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeEliminarCuentaUseCase_8 extends _i1.SmartFake
    implements _i10.EliminarCuentaUseCase {
  _FakeEliminarCuentaUseCase_8(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeAuthRepository_9 extends _i1.SmartFake
    implements _i11.AuthRepository {
  _FakeAuthRepository_9(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeGetHabitacionesUseCase_10 extends _i1.SmartFake
    implements _i12.GetHabitacionesUseCase {
  _FakeGetHabitacionesUseCase_10(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeCheckDisponibilidadUseCase_11 extends _i1.SmartFake
    implements _i13.CheckDisponibilidadUseCase {
  _FakeCheckDisponibilidadUseCase_11(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeGetTodasLasHabitacionesUseCase_12 extends _i1.SmartFake
    implements _i14.GetTodasLasHabitacionesUseCase {
  _FakeGetTodasLasHabitacionesUseCase_12(
    Object parent,
    Invocation parentInvocation,
  ) : super(parent, parentInvocation);
}

class _FakeLocale_13 extends _i1.SmartFake implements _i15.Locale {
  _FakeLocale_13(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [AuthViewModel].
///
/// See the documentation for Mockito's code generation for more information.
class MockAuthViewModel extends _i1.Mock implements _i16.AuthViewModel {
  @override
  _i2.LoginUseCase get loginUseCase =>
      (super.noSuchMethod(
            Invocation.getter(#loginUseCase),
            returnValue: _FakeLoginUseCase_0(
              this,
              Invocation.getter(#loginUseCase),
            ),
            returnValueForMissingStub: _FakeLoginUseCase_0(
              this,
              Invocation.getter(#loginUseCase),
            ),
          )
          as _i2.LoginUseCase);

  @override
  _i3.RegisterUseCase get registerUseCase =>
      (super.noSuchMethod(
            Invocation.getter(#registerUseCase),
            returnValue: _FakeRegisterUseCase_1(
              this,
              Invocation.getter(#registerUseCase),
            ),
            returnValueForMissingStub: _FakeRegisterUseCase_1(
              this,
              Invocation.getter(#registerUseCase),
            ),
          )
          as _i3.RegisterUseCase);

  @override
  _i4.GoogleSignInUseCase get googleSignInUseCase =>
      (super.noSuchMethod(
            Invocation.getter(#googleSignInUseCase),
            returnValue: _FakeGoogleSignInUseCase_2(
              this,
              Invocation.getter(#googleSignInUseCase),
            ),
            returnValueForMissingStub: _FakeGoogleSignInUseCase_2(
              this,
              Invocation.getter(#googleSignInUseCase),
            ),
          )
          as _i4.GoogleSignInUseCase);

  @override
  _i5.LogoutUseCase get logoutUseCase =>
      (super.noSuchMethod(
            Invocation.getter(#logoutUseCase),
            returnValue: _FakeLogoutUseCase_3(
              this,
              Invocation.getter(#logoutUseCase),
            ),
            returnValueForMissingStub: _FakeLogoutUseCase_3(
              this,
              Invocation.getter(#logoutUseCase),
            ),
          )
          as _i5.LogoutUseCase);

  @override
  _i6.ActualizarPerfilUseCase get actualizarPerfilUseCase =>
      (super.noSuchMethod(
            Invocation.getter(#actualizarPerfilUseCase),
            returnValue: _FakeActualizarPerfilUseCase_4(
              this,
              Invocation.getter(#actualizarPerfilUseCase),
            ),
            returnValueForMissingStub: _FakeActualizarPerfilUseCase_4(
              this,
              Invocation.getter(#actualizarPerfilUseCase),
            ),
          )
          as _i6.ActualizarPerfilUseCase);

  @override
  _i7.VincularPasswordUseCase get vincularPasswordUseCase =>
      (super.noSuchMethod(
            Invocation.getter(#vincularPasswordUseCase),
            returnValue: _FakeVincularPasswordUseCase_5(
              this,
              Invocation.getter(#vincularPasswordUseCase),
            ),
            returnValueForMissingStub: _FakeVincularPasswordUseCase_5(
              this,
              Invocation.getter(#vincularPasswordUseCase),
            ),
          )
          as _i7.VincularPasswordUseCase);

  @override
  _i8.VerificarEmailUseCase get verificarEmailUseCase =>
      (super.noSuchMethod(
            Invocation.getter(#verificarEmailUseCase),
            returnValue: _FakeVerificarEmailUseCase_6(
              this,
              Invocation.getter(#verificarEmailUseCase),
            ),
            returnValueForMissingStub: _FakeVerificarEmailUseCase_6(
              this,
              Invocation.getter(#verificarEmailUseCase),
            ),
          )
          as _i8.VerificarEmailUseCase);

  @override
  _i9.RecuperarPasswordUseCase get recuperarPasswordUseCase =>
      (super.noSuchMethod(
            Invocation.getter(#recuperarPasswordUseCase),
            returnValue: _FakeRecuperarPasswordUseCase_7(
              this,
              Invocation.getter(#recuperarPasswordUseCase),
            ),
            returnValueForMissingStub: _FakeRecuperarPasswordUseCase_7(
              this,
              Invocation.getter(#recuperarPasswordUseCase),
            ),
          )
          as _i9.RecuperarPasswordUseCase);

  @override
  _i10.EliminarCuentaUseCase get eliminarCuentaUseCase =>
      (super.noSuchMethod(
            Invocation.getter(#eliminarCuentaUseCase),
            returnValue: _FakeEliminarCuentaUseCase_8(
              this,
              Invocation.getter(#eliminarCuentaUseCase),
            ),
            returnValueForMissingStub: _FakeEliminarCuentaUseCase_8(
              this,
              Invocation.getter(#eliminarCuentaUseCase),
            ),
          )
          as _i10.EliminarCuentaUseCase);

  @override
  _i11.AuthRepository get authRepository =>
      (super.noSuchMethod(
            Invocation.getter(#authRepository),
            returnValue: _FakeAuthRepository_9(
              this,
              Invocation.getter(#authRepository),
            ),
            returnValueForMissingStub: _FakeAuthRepository_9(
              this,
              Invocation.getter(#authRepository),
            ),
          )
          as _i11.AuthRepository);

  @override
  bool get isLoading =>
      (super.noSuchMethod(
            Invocation.getter(#isLoading),
            returnValue: false,
            returnValueForMissingStub: false,
          )
          as bool);

  @override
  bool get isEmailVerified =>
      (super.noSuchMethod(
            Invocation.getter(#isEmailVerified),
            returnValue: false,
            returnValueForMissingStub: false,
          )
          as bool);

  @override
  bool get isUsuarioSoloGoogle =>
      (super.noSuchMethod(
            Invocation.getter(#isUsuarioSoloGoogle),
            returnValue: false,
            returnValueForMissingStub: false,
          )
          as bool);

  @override
  bool get isBiometricAvailable =>
      (super.noSuchMethod(
            Invocation.getter(#isBiometricAvailable),
            returnValue: false,
            returnValueForMissingStub: false,
          )
          as bool);

  @override
  bool get hasSavedCredentials =>
      (super.noSuchMethod(
            Invocation.getter(#hasSavedCredentials),
            returnValue: false,
            returnValueForMissingStub: false,
          )
          as bool);

  @override
  bool get keepSession =>
      (super.noSuchMethod(
            Invocation.getter(#keepSession),
            returnValue: false,
            returnValueForMissingStub: false,
          )
          as bool);

  @override
  bool get hasListeners =>
      (super.noSuchMethod(
            Invocation.getter(#hasListeners),
            returnValue: false,
            returnValueForMissingStub: false,
          )
          as bool);

  @override
  void setKeepSession({required bool? value}) => super.noSuchMethod(
    Invocation.method(#setKeepSession, [], {#value: value}),
    returnValueForMissingStub: null,
  );

  @override
  _i17.Future<void> checkCurrentSession() =>
      (super.noSuchMethod(
            Invocation.method(#checkCurrentSession, []),
            returnValue: _i17.Future<void>.value(),
            returnValueForMissingStub: _i17.Future<void>.value(),
          )
          as _i17.Future<void>);

  @override
  void setUsuarioActual(_i18.Usuario? usuario) => super.noSuchMethod(
    Invocation.method(#setUsuarioActual, [usuario]),
    returnValueForMissingStub: null,
  );

  @override
  _i17.Future<bool> login(String? email, String? password) =>
      (super.noSuchMethod(
            Invocation.method(#login, [email, password]),
            returnValue: _i17.Future<bool>.value(false),
            returnValueForMissingStub: _i17.Future<bool>.value(false),
          )
          as _i17.Future<bool>);

  @override
  _i17.Future<bool> register({
    required String? nombre,
    required String? email,
    required String? password,
    required String? cedula,
    DateTime? fechaNacimiento,
    String? telefono,
    String? ubicacion,
    _i19.Uint8List? fotoBytes,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#register, [], {
              #nombre: nombre,
              #email: email,
              #password: password,
              #cedula: cedula,
              #fechaNacimiento: fechaNacimiento,
              #telefono: telefono,
              #ubicacion: ubicacion,
              #fotoBytes: fotoBytes,
            }),
            returnValue: _i17.Future<bool>.value(false),
            returnValueForMissingStub: _i17.Future<bool>.value(false),
          )
          as _i17.Future<bool>);

  @override
  _i17.Future<bool> loginConGoogle() =>
      (super.noSuchMethod(
            Invocation.method(#loginConGoogle, []),
            returnValue: _i17.Future<bool>.value(false),
            returnValueForMissingStub: _i17.Future<bool>.value(false),
          )
          as _i17.Future<bool>);

  @override
  _i17.Future<void> logout() =>
      (super.noSuchMethod(
            Invocation.method(#logout, []),
            returnValue: _i17.Future<void>.value(),
            returnValueForMissingStub: _i17.Future<void>.value(),
          )
          as _i17.Future<void>);

  @override
  _i17.Future<bool> actualizarPerfil({
    required String? uid,
    String? nombre,
    String? cedula,
    DateTime? fechaNacimiento,
    String? telefono,
    String? ubicacion,
    _i19.Uint8List? fotoBytes,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#actualizarPerfil, [], {
              #uid: uid,
              #nombre: nombre,
              #cedula: cedula,
              #fechaNacimiento: fechaNacimiento,
              #telefono: telefono,
              #ubicacion: ubicacion,
              #fotoBytes: fotoBytes,
            }),
            returnValue: _i17.Future<bool>.value(false),
            returnValueForMissingStub: _i17.Future<bool>.value(false),
          )
          as _i17.Future<bool>);

  @override
  _i17.Future<bool> vincularPassword(String? password) =>
      (super.noSuchMethod(
            Invocation.method(#vincularPassword, [password]),
            returnValue: _i17.Future<bool>.value(false),
            returnValueForMissingStub: _i17.Future<bool>.value(false),
          )
          as _i17.Future<bool>);

  @override
  _i17.Future<bool> recuperarPassword(String? email) =>
      (super.noSuchMethod(
            Invocation.method(#recuperarPassword, [email]),
            returnValue: _i17.Future<bool>.value(false),
            returnValueForMissingStub: _i17.Future<bool>.value(false),
          )
          as _i17.Future<bool>);

  @override
  _i17.Future<bool> enviarVerificacionEmail() =>
      (super.noSuchMethod(
            Invocation.method(#enviarVerificacionEmail, []),
            returnValue: _i17.Future<bool>.value(false),
            returnValueForMissingStub: _i17.Future<bool>.value(false),
          )
          as _i17.Future<bool>);

  @override
  _i17.Future<bool> verificarEmail() =>
      (super.noSuchMethod(
            Invocation.method(#verificarEmail, []),
            returnValue: _i17.Future<bool>.value(false),
            returnValueForMissingStub: _i17.Future<bool>.value(false),
          )
          as _i17.Future<bool>);

  @override
  _i17.Future<bool> eliminarCuenta() =>
      (super.noSuchMethod(
            Invocation.method(#eliminarCuenta, []),
            returnValue: _i17.Future<bool>.value(false),
            returnValueForMissingStub: _i17.Future<bool>.value(false),
          )
          as _i17.Future<bool>);

  @override
  void clearError() => super.noSuchMethod(
    Invocation.method(#clearError, []),
    returnValueForMissingStub: null,
  );

  @override
  _i17.Future<bool> loginConBiometria() =>
      (super.noSuchMethod(
            Invocation.method(#loginConBiometria, []),
            returnValue: _i17.Future<bool>.value(false),
            returnValueForMissingStub: _i17.Future<bool>.value(false),
          )
          as _i17.Future<bool>);

  @override
  void addListener(_i15.VoidCallback? listener) => super.noSuchMethod(
    Invocation.method(#addListener, [listener]),
    returnValueForMissingStub: null,
  );

  @override
  void removeListener(_i15.VoidCallback? listener) => super.noSuchMethod(
    Invocation.method(#removeListener, [listener]),
    returnValueForMissingStub: null,
  );

  @override
  void dispose() => super.noSuchMethod(
    Invocation.method(#dispose, []),
    returnValueForMissingStub: null,
  );

  @override
  void notifyListeners() => super.noSuchMethod(
    Invocation.method(#notifyListeners, []),
    returnValueForMissingStub: null,
  );
}

/// A class which mocks [HosteriaViewModel].
///
/// See the documentation for Mockito's code generation for more information.
class MockHosteriaViewModel extends _i1.Mock implements _i20.HosteriaViewModel {
  @override
  List<_i21.Hosteria> get todasHosterias =>
      (super.noSuchMethod(
            Invocation.getter(#todasHosterias),
            returnValue: <_i21.Hosteria>[],
            returnValueForMissingStub: <_i21.Hosteria>[],
          )
          as List<_i21.Hosteria>);

  @override
  List<_i21.Hosteria> get hosterias =>
      (super.noSuchMethod(
            Invocation.getter(#hosterias),
            returnValue: <_i21.Hosteria>[],
            returnValueForMissingStub: <_i21.Hosteria>[],
          )
          as List<_i21.Hosteria>);

  @override
  bool get isLoading =>
      (super.noSuchMethod(
            Invocation.getter(#isLoading),
            returnValue: false,
            returnValueForMissingStub: false,
          )
          as bool);

  @override
  List<_i21.Hosteria> get destacadas =>
      (super.noSuchMethod(
            Invocation.getter(#destacadas),
            returnValue: <_i21.Hosteria>[],
            returnValueForMissingStub: <_i21.Hosteria>[],
          )
          as List<_i21.Hosteria>);

  @override
  _i20.OrdenHosterias get ordenActual =>
      (super.noSuchMethod(
            Invocation.getter(#ordenActual),
            returnValue: _i20.OrdenHosterias.ninguno,
            returnValueForMissingStub: _i20.OrdenHosterias.ninguno,
          )
          as _i20.OrdenHosterias);

  @override
  bool get hasListeners =>
      (super.noSuchMethod(
            Invocation.getter(#hasListeners),
            returnValue: false,
            returnValueForMissingStub: false,
          )
          as bool);

  @override
  List<_i21.Hosteria> obtenerCercanas(
    double? lat,
    double? lng, {
    int? count = 4,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#obtenerCercanas, [lat, lng], {#count: count}),
            returnValue: <_i21.Hosteria>[],
            returnValueForMissingStub: <_i21.Hosteria>[],
          )
          as List<_i21.Hosteria>);

  @override
  _i17.Future<void> cargarHosterias() =>
      (super.noSuchMethod(
            Invocation.method(#cargarHosterias, []),
            returnValue: _i17.Future<void>.value(),
            returnValueForMissingStub: _i17.Future<void>.value(),
          )
          as _i17.Future<void>);

  @override
  _i17.Future<void> cargarHosteriaDetalle(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#cargarHosteriaDetalle, [id]),
            returnValue: _i17.Future<void>.value(),
            returnValueForMissingStub: _i17.Future<void>.value(),
          )
          as _i17.Future<void>);

  @override
  void filtrarHosterias(String? query) => super.noSuchMethod(
    Invocation.method(#filtrarHosterias, [query]),
    returnValueForMissingStub: null,
  );

  @override
  void cambiarOrden(_i20.OrdenHosterias? orden) => super.noSuchMethod(
    Invocation.method(#cambiarOrden, [orden]),
    returnValueForMissingStub: null,
  );

  @override
  void aplicarFiltrosAvanzados({
    _i22.DateTimeRange<DateTime>? fechas,
    _i22.RangeValues? precios,
  }) => super.noSuchMethod(
    Invocation.method(#aplicarFiltrosAvanzados, [], {
      #fechas: fechas,
      #precios: precios,
    }),
    returnValueForMissingStub: null,
  );

  @override
  void limpiarFiltrosAvanzados() => super.noSuchMethod(
    Invocation.method(#limpiarFiltrosAvanzados, []),
    returnValueForMissingStub: null,
  );

  @override
  void addListener(_i15.VoidCallback? listener) => super.noSuchMethod(
    Invocation.method(#addListener, [listener]),
    returnValueForMissingStub: null,
  );

  @override
  void removeListener(_i15.VoidCallback? listener) => super.noSuchMethod(
    Invocation.method(#removeListener, [listener]),
    returnValueForMissingStub: null,
  );

  @override
  void dispose() => super.noSuchMethod(
    Invocation.method(#dispose, []),
    returnValueForMissingStub: null,
  );

  @override
  void notifyListeners() => super.noSuchMethod(
    Invocation.method(#notifyListeners, []),
    returnValueForMissingStub: null,
  );
}

/// A class which mocks [HabitacionViewModel].
///
/// See the documentation for Mockito's code generation for more information.
class MockHabitacionViewModel extends _i1.Mock
    implements _i23.HabitacionViewModel {
  @override
  _i12.GetHabitacionesUseCase get getHabitacionesUseCase =>
      (super.noSuchMethod(
            Invocation.getter(#getHabitacionesUseCase),
            returnValue: _FakeGetHabitacionesUseCase_10(
              this,
              Invocation.getter(#getHabitacionesUseCase),
            ),
            returnValueForMissingStub: _FakeGetHabitacionesUseCase_10(
              this,
              Invocation.getter(#getHabitacionesUseCase),
            ),
          )
          as _i12.GetHabitacionesUseCase);

  @override
  _i13.CheckDisponibilidadUseCase get checkDisponibilidadUseCase =>
      (super.noSuchMethod(
            Invocation.getter(#checkDisponibilidadUseCase),
            returnValue: _FakeCheckDisponibilidadUseCase_11(
              this,
              Invocation.getter(#checkDisponibilidadUseCase),
            ),
            returnValueForMissingStub: _FakeCheckDisponibilidadUseCase_11(
              this,
              Invocation.getter(#checkDisponibilidadUseCase),
            ),
          )
          as _i13.CheckDisponibilidadUseCase);

  @override
  _i14.GetTodasLasHabitacionesUseCase get getTodasLasHabitacionesUseCase =>
      (super.noSuchMethod(
            Invocation.getter(#getTodasLasHabitacionesUseCase),
            returnValue: _FakeGetTodasLasHabitacionesUseCase_12(
              this,
              Invocation.getter(#getTodasLasHabitacionesUseCase),
            ),
            returnValueForMissingStub: _FakeGetTodasLasHabitacionesUseCase_12(
              this,
              Invocation.getter(#getTodasLasHabitacionesUseCase),
            ),
          )
          as _i14.GetTodasLasHabitacionesUseCase);

  @override
  List<_i24.Habitacion> get habitaciones =>
      (super.noSuchMethod(
            Invocation.getter(#habitaciones),
            returnValue: <_i24.Habitacion>[],
            returnValueForMissingStub: <_i24.Habitacion>[],
          )
          as List<_i24.Habitacion>);

  @override
  List<_i24.Habitacion> get todasLasHabitaciones =>
      (super.noSuchMethod(
            Invocation.getter(#todasLasHabitaciones),
            returnValue: <_i24.Habitacion>[],
            returnValueForMissingStub: <_i24.Habitacion>[],
          )
          as List<_i24.Habitacion>);

  @override
  bool get isLoading =>
      (super.noSuchMethod(
            Invocation.getter(#isLoading),
            returnValue: false,
            returnValueForMissingStub: false,
          )
          as bool);

  @override
  bool get hasListeners =>
      (super.noSuchMethod(
            Invocation.getter(#hasListeners),
            returnValue: false,
            returnValueForMissingStub: false,
          )
          as bool);

  @override
  bool? getDisponibilidad(String? habitacionId) =>
      (super.noSuchMethod(
            Invocation.method(#getDisponibilidad, [habitacionId]),
            returnValueForMissingStub: null,
          )
          as bool?);

  @override
  _i17.Future<void> cargarTodasLasHabitaciones() =>
      (super.noSuchMethod(
            Invocation.method(#cargarTodasLasHabitaciones, []),
            returnValue: _i17.Future<void>.value(),
            returnValueForMissingStub: _i17.Future<void>.value(),
          )
          as _i17.Future<void>);

  @override
  _i17.Future<void> cargarHabitacionesPorHosteria(String? hosteriaId) =>
      (super.noSuchMethod(
            Invocation.method(#cargarHabitacionesPorHosteria, [hosteriaId]),
            returnValue: _i17.Future<void>.value(),
            returnValueForMissingStub: _i17.Future<void>.value(),
          )
          as _i17.Future<void>);

  @override
  _i17.Future<void> verificarDisponibilidadTodas(
    DateTime? checkIn,
    DateTime? checkOut,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#verificarDisponibilidadTodas, [
              checkIn,
              checkOut,
            ]),
            returnValue: _i17.Future<void>.value(),
            returnValueForMissingStub: _i17.Future<void>.value(),
          )
          as _i17.Future<void>);

  @override
  void addListener(_i15.VoidCallback? listener) => super.noSuchMethod(
    Invocation.method(#addListener, [listener]),
    returnValueForMissingStub: null,
  );

  @override
  void removeListener(_i15.VoidCallback? listener) => super.noSuchMethod(
    Invocation.method(#removeListener, [listener]),
    returnValueForMissingStub: null,
  );

  @override
  void dispose() => super.noSuchMethod(
    Invocation.method(#dispose, []),
    returnValueForMissingStub: null,
  );

  @override
  void notifyListeners() => super.noSuchMethod(
    Invocation.method(#notifyListeners, []),
    returnValueForMissingStub: null,
  );
}

/// A class which mocks [ReservaViewModel].
///
/// See the documentation for Mockito's code generation for more information.
class MockReservaViewModel extends _i1.Mock implements _i25.ReservaViewModel {
  @override
  List<_i26.Reserva> get reservas =>
      (super.noSuchMethod(
            Invocation.getter(#reservas),
            returnValue: <_i26.Reserva>[],
            returnValueForMissingStub: <_i26.Reserva>[],
          )
          as List<_i26.Reserva>);

  @override
  bool get isLoading =>
      (super.noSuchMethod(
            Invocation.getter(#isLoading),
            returnValue: false,
            returnValueForMissingStub: false,
          )
          as bool);

  @override
  bool get hasListeners =>
      (super.noSuchMethod(
            Invocation.getter(#hasListeners),
            returnValue: false,
            returnValueForMissingStub: false,
          )
          as bool);

  @override
  _i17.Future<bool> crearReserva(_i26.Reserva? reserva) =>
      (super.noSuchMethod(
            Invocation.method(#crearReserva, [reserva]),
            returnValue: _i17.Future<bool>.value(false),
            returnValueForMissingStub: _i17.Future<bool>.value(false),
          )
          as _i17.Future<bool>);

  @override
  _i17.Future<void> cargarHistorial(String? usuarioId) =>
      (super.noSuchMethod(
            Invocation.method(#cargarHistorial, [usuarioId]),
            returnValue: _i17.Future<void>.value(),
            returnValueForMissingStub: _i17.Future<void>.value(),
          )
          as _i17.Future<void>);

  @override
  _i17.Future<void> cargarTodasLasReservas() =>
      (super.noSuchMethod(
            Invocation.method(#cargarTodasLasReservas, []),
            returnValue: _i17.Future<void>.value(),
            returnValueForMissingStub: _i17.Future<void>.value(),
          )
          as _i17.Future<void>);

  @override
  _i17.Future<bool> actualizarEstadoReserva(
    String? reservaId,
    String? nuevoEstado,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#actualizarEstadoReserva, [
              reservaId,
              nuevoEstado,
            ]),
            returnValue: _i17.Future<bool>.value(false),
            returnValueForMissingStub: _i17.Future<bool>.value(false),
          )
          as _i17.Future<bool>);

  @override
  _i17.Future<bool> cancelarReservaUsuario(String? reservaId) =>
      (super.noSuchMethod(
            Invocation.method(#cancelarReservaUsuario, [reservaId]),
            returnValue: _i17.Future<bool>.value(false),
            returnValueForMissingStub: _i17.Future<bool>.value(false),
          )
          as _i17.Future<bool>);

  @override
  _i17.Future<bool> existeSolapamiento(
    String? usuarioId,
    DateTime? checkIn,
    DateTime? checkOut,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#existeSolapamiento, [
              usuarioId,
              checkIn,
              checkOut,
            ]),
            returnValue: _i17.Future<bool>.value(false),
            returnValueForMissingStub: _i17.Future<bool>.value(false),
          )
          as _i17.Future<bool>);

  @override
  _i17.Future<bool> verificarDisponibilidad(
    _i24.Habitacion? habitacion,
    DateTime? checkIn,
    DateTime? checkOut,
    int? cantidadSolicitada,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#verificarDisponibilidad, [
              habitacion,
              checkIn,
              checkOut,
              cantidadSolicitada,
            ]),
            returnValue: _i17.Future<bool>.value(false),
            returnValueForMissingStub: _i17.Future<bool>.value(false),
          )
          as _i17.Future<bool>);

  @override
  _i17.Future<bool> cancelarReserva(String? reservaId) =>
      (super.noSuchMethod(
            Invocation.method(#cancelarReserva, [reservaId]),
            returnValue: _i17.Future<bool>.value(false),
            returnValueForMissingStub: _i17.Future<bool>.value(false),
          )
          as _i17.Future<bool>);

  @override
  void addListener(_i15.VoidCallback? listener) => super.noSuchMethod(
    Invocation.method(#addListener, [listener]),
    returnValueForMissingStub: null,
  );

  @override
  void removeListener(_i15.VoidCallback? listener) => super.noSuchMethod(
    Invocation.method(#removeListener, [listener]),
    returnValueForMissingStub: null,
  );

  @override
  void dispose() => super.noSuchMethod(
    Invocation.method(#dispose, []),
    returnValueForMissingStub: null,
  );

  @override
  void notifyListeners() => super.noSuchMethod(
    Invocation.method(#notifyListeners, []),
    returnValueForMissingStub: null,
  );
}

/// A class which mocks [LocaleViewModel].
///
/// See the documentation for Mockito's code generation for more information.
class MockLocaleViewModel extends _i1.Mock implements _i27.LocaleViewModel {
  @override
  _i15.Locale get locale =>
      (super.noSuchMethod(
            Invocation.getter(#locale),
            returnValue: _FakeLocale_13(this, Invocation.getter(#locale)),
            returnValueForMissingStub: _FakeLocale_13(
              this,
              Invocation.getter(#locale),
            ),
          )
          as _i15.Locale);

  @override
  bool get hasListeners =>
      (super.noSuchMethod(
            Invocation.getter(#hasListeners),
            returnValue: false,
            returnValueForMissingStub: false,
          )
          as bool);

  @override
  void setLocale(_i15.Locale? locale) => super.noSuchMethod(
    Invocation.method(#setLocale, [locale]),
    returnValueForMissingStub: null,
  );

  @override
  void toggleLanguage() => super.noSuchMethod(
    Invocation.method(#toggleLanguage, []),
    returnValueForMissingStub: null,
  );

  @override
  void addListener(_i15.VoidCallback? listener) => super.noSuchMethod(
    Invocation.method(#addListener, [listener]),
    returnValueForMissingStub: null,
  );

  @override
  void removeListener(_i15.VoidCallback? listener) => super.noSuchMethod(
    Invocation.method(#removeListener, [listener]),
    returnValueForMissingStub: null,
  );

  @override
  void dispose() => super.noSuchMethod(
    Invocation.method(#dispose, []),
    returnValueForMissingStub: null,
  );

  @override
  void notifyListeners() => super.noSuchMethod(
    Invocation.method(#notifyListeners, []),
    returnValueForMissingStub: null,
  );
}

/// A class which mocks [WeatherViewModel].
///
/// See the documentation for Mockito's code generation for more information.
class MockWeatherViewModel extends _i1.Mock implements _i28.WeatherViewModel {
  @override
  bool get isLoading =>
      (super.noSuchMethod(
            Invocation.getter(#isLoading),
            returnValue: false,
            returnValueForMissingStub: false,
          )
          as bool);

  @override
  bool get hasListeners =>
      (super.noSuchMethod(
            Invocation.getter(#hasListeners),
            returnValue: false,
            returnValueForMissingStub: false,
          )
          as bool);

  @override
  _i17.Future<void> fetchWeather() =>
      (super.noSuchMethod(
            Invocation.method(#fetchWeather, []),
            returnValue: _i17.Future<void>.value(),
            returnValueForMissingStub: _i17.Future<void>.value(),
          )
          as _i17.Future<void>);

  @override
  _i22.IconData getWeatherIcon() =>
      (super.noSuchMethod(
            Invocation.method(#getWeatherIcon, []),
            returnValue: _i29.dummyValue<_i22.IconData>(
              this,
              Invocation.method(#getWeatherIcon, []),
            ),
            returnValueForMissingStub: _i29.dummyValue<_i22.IconData>(
              this,
              Invocation.method(#getWeatherIcon, []),
            ),
          )
          as _i22.IconData);

  @override
  void addListener(_i15.VoidCallback? listener) => super.noSuchMethod(
    Invocation.method(#addListener, [listener]),
    returnValueForMissingStub: null,
  );

  @override
  void removeListener(_i15.VoidCallback? listener) => super.noSuchMethod(
    Invocation.method(#removeListener, [listener]),
    returnValueForMissingStub: null,
  );

  @override
  void dispose() => super.noSuchMethod(
    Invocation.method(#dispose, []),
    returnValueForMissingStub: null,
  );

  @override
  void notifyListeners() => super.noSuchMethod(
    Invocation.method(#notifyListeners, []),
    returnValueForMissingStub: null,
  );
}

/// A class which mocks [NotificacionViewModel].
///
/// See the documentation for Mockito's code generation for more information.
class MockNotificacionViewModel extends _i1.Mock
    implements _i30.NotificacionViewModel {
  @override
  List<_i31.NotificacionApp> get notificaciones =>
      (super.noSuchMethod(
            Invocation.getter(#notificaciones),
            returnValue: <_i31.NotificacionApp>[],
            returnValueForMissingStub: <_i31.NotificacionApp>[],
          )
          as List<_i31.NotificacionApp>);

  @override
  bool get isLoading =>
      (super.noSuchMethod(
            Invocation.getter(#isLoading),
            returnValue: false,
            returnValueForMissingStub: false,
          )
          as bool);

  @override
  bool get hasListeners =>
      (super.noSuchMethod(
            Invocation.getter(#hasListeners),
            returnValue: false,
            returnValueForMissingStub: false,
          )
          as bool);

  @override
  void listenToNotificaciones(String? usuarioId) => super.noSuchMethod(
    Invocation.method(#listenToNotificaciones, [usuarioId]),
    returnValueForMissingStub: null,
  );

  @override
  _i17.Future<void> marcarLeida(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#marcarLeida, [id]),
            returnValue: _i17.Future<void>.value(),
            returnValueForMissingStub: _i17.Future<void>.value(),
          )
          as _i17.Future<void>);

  @override
  _i17.Future<void> marcarTodasComoLeidas(String? usuarioId) =>
      (super.noSuchMethod(
            Invocation.method(#marcarTodasComoLeidas, [usuarioId]),
            returnValue: _i17.Future<void>.value(),
            returnValueForMissingStub: _i17.Future<void>.value(),
          )
          as _i17.Future<void>);

  @override
  _i17.Future<void> borrarTodas(String? usuarioId) =>
      (super.noSuchMethod(
            Invocation.method(#borrarTodas, [usuarioId]),
            returnValue: _i17.Future<void>.value(),
            returnValueForMissingStub: _i17.Future<void>.value(),
          )
          as _i17.Future<void>);

  @override
  void dispose() => super.noSuchMethod(
    Invocation.method(#dispose, []),
    returnValueForMissingStub: null,
  );

  @override
  void addListener(_i15.VoidCallback? listener) => super.noSuchMethod(
    Invocation.method(#addListener, [listener]),
    returnValueForMissingStub: null,
  );

  @override
  void removeListener(_i15.VoidCallback? listener) => super.noSuchMethod(
    Invocation.method(#removeListener, [listener]),
    returnValueForMissingStub: null,
  );

  @override
  void notifyListeners() => super.noSuchMethod(
    Invocation.method(#notifyListeners, []),
    returnValueForMissingStub: null,
  );
}
